version: "3.5"

services:
  opsdroid:
    image: opsdroid/opsdroid:v0.28.0
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./configuration.yaml:/root/.config/opsdroid/configuration.yaml
      - ./:/root/.skills/skill-docker-daemon
